version: "3.5"

services:
  php_fpm:
    build: ./docker/php-fpm
    container_name: rpg_php_fpm
    working_dir: /var/www/html/rpg-admin
    networks:
      - rpg_network
    volumes:
      - ./:/var/www/html/rpg-admin

  nginx:
    build: ./docker/nginx
    container_name: rpg_nginx
    working_dir: /var/www/html/rpg-admin
    networks:
      - rpg_network
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/rpg-admin
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: rpg_mysql
    networks:
      - rpg_network
    environment:
      - MYSQL_DATABASE=rpg_admin
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret

  mailhog:
    build: ./docker/mailhog
    container_name: rpg_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rpg_network

networks:
  rpg_network:
    driver: bridge
